title: 'Sistemas y Tecnologías Web: Servidor'
subtitle: 'Master de Ingeniería Informática'
#remote_theme: mmistakes/minimal-mistakes
#minimal_mistakes_skin: "plum" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
theme: jekyll-theme-midnight
description: 'Master de II. ULL. 1er cuatrimestre'
future: true
baseurl: ""
include: [".nojekyll"]
skin: "white" # "light" # change theme to midday instead of night
exclude: 
  - Gemfile # to avoid messages from GH dependences
  - Gemfile.lock
  - node_modules
  - tema3-web/practicas/p10-t3-commanding-databases/eval
  - tema2-async/practicas/p7-t2-asyncmap/sol-reto-async-reading-multiple-files
  - tema2-async/practicas/p9-t2-promise-readfile/solution/casiano
  - tema2-async/practicas/p10-t2-promise-all/solution
  - tema2-async/event-loop/exercises/promises/promise-all
show_downloads: false
live_reload: true
organization: 
  url: https://github.com/ULL-MII-SYTWS-2122
  name: ULL-MII-SYTWS-2122
  master: https://github.com/ULL-MII-SYTWS-2122/tree/master/
chat: https://chat.google.com/u/1/room/AAAAp18fCE8
jamboard: https://jamboard.google.com/d/1wCWvYJeirSY7ISGO80Ip6h-k_1FH_XYDuUtqe0jf5Fk/edit?usp=sharing
classroom:
  url: https://classroom.github.com/classrooms/90842007-ull-mii-sytws-2122 #https://classroom.github.com/classrooms/68184806-ull-mii-sytws-2021
  name: ULL-MII-SYTWS-2122
  id: 90842007 # 68184806
collections: 
  practicas: 
    output: true
    sorted_by: order
campus_virtual:
  home: https://campusdoctoradoyposgrado2122.ull.es/course/view.php?id=2122110810  # https://campusdoctoradoyposgrado.ull.es/course/view.php?id=2122110810 
  tareas: 
calificador: 
covid_ull: https://campusvirtual.ull.es/doctoradoyposgrado/course/view.php?id=201913946
horarios_tutorias: https://docs.google.com/spreadsheets/d/1ZTGvLA70qCYEsBwcA8dCiUZby3ZOM9oHt8kmiNNKId0/edit#gid=0
github_org: https://github.com/ULL-MII-SYTWS-2122
repo_apuntes: https://github.com/ULL-MII-SYTWS/ull-mii-sytws.github.io-source/
repo_url_master: https://github.com/ULL-MII-SYTWS/ull-mii-sytws.github.io-source/tree/main/
despliegue_apuntes: https://ull-mii-sytws.github.io/
#classroom: https://classroom.github.com/classrooms/55384072-master-de-ingenieria-informatica-sistemas-y-tecnologias-web-servidor-classroom
profesor: https://www.ull.es/apps/guias/guias/view_teacher_niu/837/crguezl/ # https://www.ull.es/apps/guias/guias/view_teacher_niu/745/(%3FPcrguezl.*)/
profesor_name: Casiano
acronimo: SYTWS
acronimo_curso: SYTWS 19/20
comments: true
start_date: "September 28, 2020"
disqus: https://https-ull-mii-sytws-1920-github-io.disqus.com/embed.js
bull_permanente: https://puntoq.ull.es/permalink/f
temas:
  - path: tema0-presentacion
    title: "La Asignatura SYTWS "
  - path: tema2-async
    title: "Computación Asíncrona y Distribuída"
  - path: tema1-introduccion
    title: "Node.JS"
  - path: tema3-web
    title: "Servicios y Aplicaciones Web"
  - path: tema4-devops
    title: "Introducción a Docker"
books_shared: https://github.com/ULL-MII-SYTWS-2122/books-shared/tree/master/
books_shared_2019: https://github.com/ULL-MII-SYTWS-1920/books-shared/tree/master/
meet: https://meet.google.com/bhv-togn-ynm
kramdown:
  input:          GFM
  # https://github.com/jekyll/jekyll/pull/4090
  syntax_highlighter: rouge

  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # span, block element options fall back to global
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'codehilite' # 'highlight'
    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1